### ISSUE TITLE
Calibration and Alignment 

### ISSUE THREAD

**Issue by KingOfDranovis** [BifrostXR/Pulse#1]
I started up SteamVR, calibrated both hands and aligned them, but when I restarted SteamVR due to a game opening in Oculus mode instead of SteamVR mode, I noticed that the alignment of my hands were reset to be exactly where my actual controllers were. This wasn't because of the game itself, as aligning my hands again and restarting SteamVR had the same result. This was very annoying to deal with because the alignment and calibration buttons are hard to use with the gloves on, especially due to the fact that I can't currently open the SteamVR dashboard to see my desktop screen. 

Related to this, the calibration seemed to give very different results on each hand, the pinky finger on my right hand was extremely loose compared to the rest of the fingers and the left hand just felt overall tighter than the right. 

I also suggest putting the alignment on a timer, maybe ten to fifteen seconds, just because trying to align where your hand is in VR is very difficult when you can't easily click the alignment button while doing that. Maybe with an audio cue like how the SlimeVR app does calibration?

**Comment by BifrostXR** [comment]
Many of these issues are fixed in the new release!
