### ISSUE TITLE
It won't open the UI

### ISSUE THREAD

**Issue by Recon3611** [BifrostXR/Pulse#2]
I extract the file run the install.bat steamVR opens but not the pulse UI.
Do you have a fix for this?
I've restarted my pc, uninstalled/reinstalled and I can't get it to work.

**Comment by BifrostXR** [comment]
Please check your SteamVR directory to make sure it installed correctly. The default location is C:\Program Files (x86)\Steam\steamapps\common\SteamVR

**Comment by Recon3611** [comment]
I'ts there and it still isn't working.

**Comment by BifrostXR** [comment]
Is the driver showing up in SteamVR settings?

**Comment by Recon3611** [comment]
Yes.

**Comment by BifrostXR** [comment]
Do the device icons appear in the SteamVR Status window? Can you please send screenshots so that we can help resolve this issue.

**Comment by Recon3611** [comment]
v0.1.50 fixed it thanks!
